### ISSUE TITLE
Undocumented feature: actions on transitions

### ISSUE THREAD

**Issue by AleLovesio** [nbattezzati/fsml#21]
FSML provides the feature to assign instructions to be executed on state transitions, however this feature is undocumented.
For example, to following code is allowed:
`on (condition) { printf("I'm on a transition!\n"); } go NEXT_STATE;`

However the README does not document this usage.

**Comment by nbattezzati** [comment]
Thank you for pointing that out. Actually, user code on transitions can be specified as explained in the "User-specific Code" section of the README. Closing issue.
