### ISSUE TITLE
"multiple definition" linking error for input setters functions 

### ISSUE THREAD

**Issue by AlessandroLovesio** [nbattezzati/fsml#27]
In case two or more FSML-generated state machines are linked together within the same executable, the linker gives a "multiple definition" error because the input setters functions of variables with the same name between different FSMs are indentical

**Comment by AlessandroLovesio** [comment]
May be fixed by changing [this line](https://github.com/nbattezzati/fsml/blob/32ba33a4428d526e5ce42466f6308fbc67d725fe/src/FSML2CCompiler.cpp#L238)   
`  in_functions += "void __set_" + v->Name() + "(" + v->Type() + ");\n";`
into this 
 `  in_functions += "void @PREFIX@__set_" + v->Name() + "(" + v->Type() + ");\n";;`

and  [this line](https://github.com/nbattezzati/fsml/blob/32ba33a4428d526e5ce42466f6308fbc67d725fe/src/FSML2CCompiler.cpp#L273)   
 `  ret_str += "   .set_" + v->Name() + " = __set_" + v->Name();`
into this 
 `  ret_str += "   .set_" + v->Name() + " = @PREFIX@__set_" + v->Name();`

and  [this line](https://github.com/nbattezzati/fsml/blob/32ba33a4428d526e5ce42466f6308fbc67d725fe/src/FSML2CCompiler.cpp#L528)   
                    `  in_functions += "void __set_" + v->Name() + "(" + v->Type() + " input)\n";;`
into this 
 `  in_functions += "void @PREFIX@__set_" + v->Name() + "(" + v->Type() + " input)\n";`

The same actually applies to the getter functions close to the setters.

**Comment by nbattezzati** [comment]
@AlessandroLovesio you could have the honour to become a Contributor, just having a Pull Request integrated in the mainline. I encourgae you go on and try it 😝 ahahahaha
